### ISSUE TITLE
Why do you need docker inside docker ?

### ISSUE THREAD

**Issue by defender** [wtsi-hgi/docker-proxify#4]
Hi

First of all this is a great solution, my question is why do you need another instance of docker why cant you use external docker docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):$(which docker) –v /lib64/libdevmapper.so.1.02:/lib/x86_64-linux-gnu/libdevmapper.so.1.02 
-v /lib64/libudev.so.0.5.1:/lib/x86_64-linux-gnu/libudev.so.0.5.1 --privileged
 , this way you can
1. Simplify your installtion
2. You will be on the same page regarding versions of docker host & your solution
3. You will remove unnecessary downloads of existing images on your instance and you will use parent docker images.

Thanks

**Comment by wtsi-mercury** [comment]
It seems like that might work, but I haven't tried it. I was following the pattern for docker-in-docker suggested by Jérôme Petazzoni (https://blog.docker.com/2013/09/docker-can-now-run-within-docker/), because I wanted to start from something known to work and then layer the transparent proxying on top of that. If you can get it to work without fully encapsulating the inner docker, that might be useful to some people - feel free to fork and modify!

**Comment by jrandall** [comment]
A few more things about docker-in-docker:
 - a primary use case for us was supporting `docker build` steps that required the proxy server (not just `docker run`)
 - I think your third point above isn't a problem because the docker graph/image db will be shared between the outer and inner docker
