### ISSUE TITLE
Proxying outgoing connection to a proxy

### ISSUE THREAD

**Issue by pilgrim2go** [wtsi-hgi/docker-proxify#5]
Hi,

I have question here

[http://stackoverflow.com/questions/37939876/proxying-docker-container-for-outgoing-connections
](http://stackoverflow.com/questions/37939876/proxying-docker-container-for-outgoing-connections)

Can this tool help to resolve it?
Per intro here [http://www.sanger.ac.uk/science/tools/docker-proxify](url) 
it matchs my need.

Can you help update documentation to give it an example?

Thanks

**Comment by jrandall** [comment]
@pilgrim2go yes, from the sound of your problem I think that `docker-proxify` would be an alternative solution to your iptables based method of transparent proxying. 

Thankfully (for us) we no longer have the problem that our docker hosts are trapped in a network from which they can only access the outside world via a proxy server, so unfortunately (for you) we no longer have a reason to maintain the code. It definitely worked as of ~2 years ago, but that was with a pre-1.0 version of docker. I think there is a good chance that it may still work with current docker versions, but I haven't tested it because we don't need it here any more. 

I would suggest that you give it a try and if it does not work, give details of what is happening and I'll help if I can.
